In [ ]:
import pandas as pd

In [ ]:
pd.read_csv("cars.csv")

***if columns name of your data  given in first row instead of mentioning so at that time you can use header***

In [ ]:
df = pd.read_csv("cars.csv",header = 1)

In [ ]:
df

***Scraping dataset from github **This Is Code You Should Use** You don't have to remeber just copy paste***

*****raw.githubusercontent.com / user / repo / branch / file_path*****

In [ ]:
import pandas as pd
import requests
from io import StringIO
## Alwys Use "//.rawgithubusercontent.com" before ".github" and remove/blob/
url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day15%20-%20working%20with%20csv%20files/aug_train.csv"

headers = {
"User-Agent":"Mozilla/5.0(Macintosh;Intel Mac OS X 10.14;rv:66.0) Gecko/20100101 Firefox/66.0"
}

req = requests.get(url, headers=headers)

data = StringIO(req.text)

df = pd.read_csv(data)

In [ ]:
df.head()

In [ ]:
df.to_csv("aug_train.csv",index=False)

***Use "sep" :- for seprator and "names" to give new col name***

In [16]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day15%20-%20working%20with%20csv%20files/movie_titles_metadata.tsv"

headers = {
"User-Agent":"Mozilla/5.0(Macintosh;Intel Mac OS X 10.14;rv:66.0) Gecko/20100101 Firefox/66.0"
}

req = requests.get(url, headers=headers)

data = StringIO(req.text)

df = pd.read_csv(data, sep="\t",
names=['sno','name','release_year','rating','votes','genres'])

print(df.head())

  sno                        name release_year  rating     votes  \
0  m0  10 things i hate about you         1999     6.9   62847.0
1  m1  1492: conquest of paradise         1992     6.2   10421.0
2  m2                  15 minutes         2001     6.1   25854.0
3  m3       2001: a space odyssey         1968     8.4  163227.0
4  m4                     48 hrs.         1982     6.9   22289.0

                                           genres
0                            ['comedy' 'romance']
1     ['adventure' 'biography' 'drama' 'history']
2           ['action' 'crime' 'drama' 'thriller']
3                ['adventure' 'mystery' 'sci-fi']
4  ['action' 'comedy' 'crime' 'drama' 'thriller']

In [18]:
df.head()

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']

In [20]:
df.to_csv("movies_data.csv",index = False)

***if You Want go use sno as index Number***

In [24]:
df = pd.read_csv("movies_data.csv",index_col="sno")

In [26]:
df.head()

,name,release_year,rating,votes,genres
sno,,,,,
m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']

***When You Want To Use Only Specific Columns Tha You Can use "usecols"***

In [45]:
df = pd.read_csv("aug_train.csv",usecols = ["enrollee_id","gender"])

In [47]:
df.head()

   enrollee_id gender
0         8949   Male
1        29725   Male
2        11561    NaN
3        33241    NaN
4          666   Male

***If You To accecess n_rows in chunks***

In [56]:
pd.read_csv('aug_train.csv',nrows = 1000)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,28500,city_21,0.624,NaN,Has relevent experience,Full time course,Graduate,STEM,<1,500-999,Pvt Ltd,1,22,0.0
996,10371,city_103,0.920,Female,No relevent experience,no_enrollment,Phd,STEM,7,500-999,Public Sector,4,28,0.0
997,10028,city_73,0.754,Male,Has relevent experience,no_enrollment,Graduate,STEM,15,1000-4999,Pvt Ltd,1,42,0.0
998,29671,city_40,0.776,Male,No relevent experience,Full time course,Graduate,STEM,9,NaN,NaN,1,50,0.0
999,4482,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10/49,Funded Startup,1,105,0.0

*Sometime You HAve to encode Your datset because in dataset there is some encoding word which are not access directly so we have to use encoding ***encoding = 'latin-1' and there is many more*** Encoding is important*

In [62]:
pd.read_csv("cars.csv",encoding = 'latin-1')

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

***if during encoding there is line which are not  encoded so skip that line***

In [67]:
pd.read_csv("cars.csv", encoding='latin-1', on_bad_lines='skip')

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

***For handling dates there is parameter parse_dates***

pd.read_csv("File_name",parse_dates = ['date'/(col_names)]).info()